### ISSUE TITLE
Access denied with 

### ISSUE THREAD

**Issue by marriusco** [varigit/var-host-docker-containers#5]
I get

```
OR: PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workdir/var-fsl-yocto/sources/poky/bitbake/bin/bitbake-worker", line 275, in child
    bb.utils.disable_network(uid, gid)
  File "/workdir/var-fsl-yocto/sources/poky/bitbake/lib/bb/utils.py", line 1693, in disable_network
    with open("/proc/self/uid_map", "w") as f:
PermissionError: [Errno 1] Operation not permitted
```

https://variwiki.com/index.php?title=Yocto_Build_Release&release=mx8mm-yocto-mickledore-6.1.36_2.1.0-v1.2

**Comment by nsdrude** [comment]
Hi Marius,

Please open a ticket in our customer support portal: https://www.variscite.com/support/

Thanks
